<wsdl:definitions name="dbAuth" targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Temp-OSB/UtilAuthentication/dbAuth" xmlns:tns="http://xmlns.oracle.com/pcbpel/adapter/db/Temp-OSB/UtilAuthentication/dbAuth" xmlns:jca="http://xmlns.oracle.com/pcbpel/wsdl/jca/" xmlns:plt="http://schemas.xmlsoap.org/ws/2003/05/partner-link/" xmlns:top="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbAuth" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/">
  <plt:partnerLinkType name="dbAuth_plt">
    <plt:role name="dbAuth_role">
      <plt:portType name="tns:dbAuth_ptt"/>
    </plt:role>
  </plt:partnerLinkType>
    <wsdl:types>
      <schema xmlns="http://www.w3.org/2001/XMLSchema">
        <import namespace="http://xmlns.oracle.com/pcbpel/adapter/db/top/dbAuth" schemaLocation="dbAuth_table.xsd"/>
      </schema>
    </wsdl:types>
    <wsdl:message name="dbAuthSelect_inputParameters">
        <wsdl:part name="dbAuthSelect_inputParameters" element="top:dbAuthSelect_ciCode_caCodeInputParameters"/>
    </wsdl:message>
    <wsdl:message name="AuthCollection_msg">
        <wsdl:part name="AuthCollection" element="top:AuthCollection"/>
    </wsdl:message>
    <wsdl:portType name="dbAuth_ptt">
        <wsdl:operation name="dbAuthSelect">
            <wsdl:input message="tns:dbAuthSelect_inputParameters"/>
            <wsdl:output message="tns:AuthCollection_msg"/>
        </wsdl:operation>
    </wsdl:portType>
</wsdl:definitions>