<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Temporarry/PaymentGWDrct/updatePayment" name="updatePayment-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="updatePayment.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Temporarry/PaymentGWDrct/updatePayment"/>
    <wsdl:binding name="updatePayment_ptt-binding" type="upd:updatePayment_ptt" xmlns:upd="http://xmlns.oracle.com/pcbpel/adapter/db/Temporarry/PaymentGWDrct/updatePayment">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="updatePayment">
            <soap:operation soapAction="updatePayment"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>