<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Temporarry/PaymentGWAuth/Logging" name="Logging-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="Logging.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Temporarry/PaymentGWAuth/Logging"/>
    <wsdl:binding name="Logging_ptt-binding" type="log:Logging_ptt" xmlns:log="http://xmlns.oracle.com/pcbpel/adapter/db/Temporarry/PaymentGWAuth/Logging">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="Logging">
            <soap:operation soapAction="Logging"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>