<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/Temp-OSB/PaymentGWAuth/serviceStatus" name="serviceStatus-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="serviceStatus.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/Temp-OSB/PaymentGWAuth/serviceStatus"/>
    <wsdl:binding name="serviceStatus_ptt-binding" type="ser:serviceStatus_ptt" xmlns:ser="http://xmlns.oracle.com/pcbpel/adapter/db/Temp-OSB/PaymentGWAuth/serviceStatus">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="serviceStatus">
            <soap:operation soapAction="serviceStatus"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>